### ISSUE TITLE
Demo scenes not working

### ISSUE THREAD

**Issue by s4l4x** [JScott/cardboard-controls#22]
The included demo scenes are not working. Prefabs and scripts are not linked.

**Comment by JScott** [comment]
Did you load it via the [latest unitypackage](https://github.com/JScott/cardboard-controls/releases/latest)? I didn't include the meta files in the repo so you can't build it with just the code. The unitypackage will handle linking everything for you, however. Also be sure to [remove old files](https://github.com/JScott/cardboard-controls/tree/master/CardboardControl#usage).

**Comment by j2l** [comment]
It's working fine for me, Unity 5.4b on Win10.
