### ISSUE TITLE
Use base SDK to improve TriggerState detection

### ISSUE THREAD

**Issue by JScott** [JScott/cardboard-controls#24]
There's been a long-running problem with CC+ where it's very difficult to differentiate between up and down. I generally assume that the first change of state is down but that's not always correct. This leads to things like `ResetMagnetState()` being a necessity.

I've been wondering for a while if I could leverage that the base SDK can tell me when the trigger has come back up to be more precise. In pseudo-code it'd be something like:

```
private TriggerState CheckTriggerState() {
  if (TriggerMoved()) {
    return BaseCardboardSDKMagnetTriggered() ? TriggerState.Up : TriggerState.Down;
  }
}
```

Note that theoretically we can remove the idea of TriggerState.Neutral and be able to say in absolute terms whether or not it's Up or Down instead of "Positive" and "Negative".

I'm sure it's not as easy as all of that but the idea is pretty simple.

**Comment by j2l** [comment]
Interesting. My iBlue plastic cardboard has magnet default state "almost up", so I get a continuous down state (like holding down) when going "upper than up then back to default". Funny

**Comment by JScott** [comment]
Someone told me that they removed magnet trigger detection from the GVR SDK. Until someone proves them wrong I'm going to close this.
