### ISSUE TITLE
could not make it work with UI buttons

### ISSUE THREAD

**Issue by j2l** [JScott/cardboard-controls#25]
Sorry, I thought it was working with UI buttons but it's not.
The raycast sees nothing when aiming at a button.

**Comment by j2l** [comment]
ok, it's working but I have shift between the button and the reticle

**Comment by j2l** [comment]
Fixed after reading notes in GVR scripts :)

**Comment by JScott** [comment]
Haha glad to hear that it worked itself out. I haven't messed with UI buttons much but there seemed to be a lot of specialized docs to make them work with the Cardboard SDK.

Do you mind linking to those notes in case someone else runs into a similar issue? They have all the scripts on GitHub which will let you link to specific lines in files.

**Comment by j2l** [comment]
Sorry, I had to close MonoDevelop, I can't remember which one but it's in the prologue comments. There are many useful info and like user's manual, I'm the kind of person not reading them :)

**Comment by JScott** [comment]
Good to know. Thanks for following up :)
