### ISSUE TITLE
Gaze collision with UI elements?

### ISSUE THREAD

**Issue by Fygo** [JScott/cardboard-controls#7]
Hi there!

Is there a way to make this plugin work with UI elements out of the box?
I am trying to measure the gaze time and it seems to work perfectly with 3D objects when their collider is enabled but I have no such luck with UI.
Thanks a lot!

**Comment by JScott** [comment]
Are you using Google's [recommendations for world space UI](https://developers.google.com/cardboard/unity/guide#gui_in_vr)? I haven't personally tried it but it seems to do what you want it to do and the guide mentions interacting with gaze triggers. Unfortunately, out-of-the-box Unity UI stuff probably won't work very well with VR in general.

**Comment by JScott** [comment]
I'm going to close this ticket under the assumption that Google's advice will work. Let me know if it doesn't and I can reopen it and consider other solutions.
