### ISSUE TITLE
Prefab is missing 4 scripts

### ISSUE THREAD

**Issue by schpitz** [JScott/cardboard-controls#8]
The script references of 4 scripts of the prefab are missing (and also all the scripts from the demo scene).
I've tried to re-import the project again, once before importing Google Cardboard sdk and once after, both shows the demo scene is broken.
BTW, demo scene has a "Missing Prefab" object, i guess this is the CardboardControlManager object.

What scripts should I link into this object?
and what about the 2 other scripts? to what object should I link them?

**Comment by JScott** [comment]
Issue #5 was the same problem I think. That was fixed when they imported the .unitypackage for the [latest release](https://github.com/JScott/cardboard-controls/releases/tag/v3.0), so we could start there to see if that works.

Either way, I'm curious what's causing this as you're not the only person to experience it. I couldn't personally recreate it and I imagine it has to do with Unity project data, which I don't include in this repo. I could try pushing the whole Unity project path to a branch if you're up for seeing if that works. That would at least determine if it's a Unity data problem or not.

**Comment by schpitz** [comment]
Consider pack the whole project into a unitypackage file, hopefully it will fix this specific issue (and it saves all the inner links).
Usually projects on github work fine, but from time to time those kind of error occurs (it also sometimes happens when trying to copy & paste a whole project at dropbox, but I couldn't find exactly what causing it).
BTW, i'm using Unity v5.0.2f1

**Comment by JScott** [comment]
So did the unitypackage in the releases section work for you? If so then I should probably call it out in the readme as the proper way to install.

**Comment by schpitz** [comment]
Yap!
Now it works great. Thanks :+1: 

I was looking for it at the github rep source-files instead of the latest release section, so it's my mistake.
I suggest you should keep using the UnityPackge file in your future releases as well, who knows how many people has the same problem.

**Comment by JScott** [comment]
Glad to hear it and thanks for reporting this :)

I'll keep this open as a reminder to myself until I make the unitypackage the obvious installation process.

**Comment by JScott** [comment]
Usage is the first thing on the README now and has a small disclaimer.
